### ISSUE TITLE
Default configuration can run out of filenames and signal error without explanation

### ISSUE THREAD

**Issue by alphapapa** [thisirs/find-temp-file#1]
I've enjoyed using this package for years.  Suddenly when I tried to use it now to make a temporary `txt` file, I got an error:

```
make-directory: Wrong type argument: stringp, ("alpha" "bravo" "charlie" "delta" "echo" "foxtrot" "golf" "hotel" "india" "juliet" ...)
```

That seemed very strange.  After using Edebug on the code, I found that the filename it was trying to create already exists in `/tmp`.  Unfortunately, the default template does not contain any timestamp info, so filenames end up being reused over a period of time.  In this case, the filename it was trying to create had been created several weeks ago and had not yet been removed by the system's automatically cleaning `/tmp`.

An easy fix for this would be to include timestamp information in the data used to calculate the hash appended to the readable word.

Of course, I can make a change like that in my config, but this raises another issue: the settings are all `defvar`s, so they don't appear in the customization system.  I had to refer to the source code to find them (I've had this package installed for like 5 years and have never had to look up the docs before).

So, if I may, I'd suggest 3 changes:

1.  Make relevant options `defcustom`s for easy customization and discovery.
2.  Include timestamp information in the default template to avoid filename conflicts.
3.  Improve the error handling: if a temporary file can't be created for whatever reason (such as an existent filename), a helpful error should be shown.

Thanks for your work on this package.  I use it all the time!

**Comment by thisirs** [comment]
Glad you like `find-temp-file`!

Looking at my local repo, it appears that I already have `defcustom`s but did not even commit them... So first point is done! :muscle:

Point 3. is indeed a bug that returns whatever returns `mapc` if no `found` exception is triggered. Simplest fix is to throw an error just atfer the `mapc`. Agreed an 2., I can add a `%U` template that expands to a timestamp dependent 5-long string and make it default

PR coming.

Thanks!

**Comment by alphapapa** [comment]
Thank you very much!

FYI, you don't need to specify the `:group` in `defcustom` forms, because the `defgroup` previously defined in the file is used automatically.

**Comment by alphapapa** [comment]
Thanks!
